/*
 *  Lib(X)SVF  -  A library for implementing SVF and XSVF JTAG players
 *
 *  Copyright (C) 2009  RIEGL Research ForschungsGmbH
 *  Copyright (C) 2009  Clifford Wolf <clifford@clifford.at>
 *
 *  Permission to use, copy, modify, and/or distribute this software for any
 *  purpose with or without fee is hereby granted, provided that the above
 *  copyright notice and this permission notice appear in all copies.
 *  
 *  THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
 *  WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
 *  MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
 *  ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
 *  WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
 *  ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
 *  OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
 *
 */

#ifndef LIBXSVF_H
#define LIBXSVF_H


enum libxsvf_tap_state {
	/* Special States */
	LIBXSVF_TAP_INIT = 0,
	LIBXSVF_TAP_RESET = 1,
	LIBXSVF_TAP_IDLE = 2,
	/* DR States */
	LIBXSVF_TAP_DRSELECT = 3,
	LIBXSVF_TAP_DRCAPTURE = 4,
	LIBXSVF_TAP_DRSHIFT = 5,
	LIBXSVF_TAP_DREXIT1 = 6,
	LIBXSVF_TAP_DRPAUSE = 7,
	LIBXSVF_TAP_DREXIT2 = 8,
	LIBXSVF_TAP_DRUPDATE = 9,
	/* IR States */
	LIBXSVF_TAP_IRSELECT = 10,
	LIBXSVF_TAP_IRCAPTURE = 11,
	LIBXSVF_TAP_IRSHIFT = 12,
	LIBXSVF_TAP_IREXIT1 = 13,
	LIBXSVF_TAP_IRPAUSE = 14,
	LIBXSVF_TAP_IREXIT2 = 15,
	LIBXSVF_TAP_IRUPDATE = 16
};

enum libxsvf_mem {
	LIBXSVF_MEM_XSVF_TDI_DATA = 0,
	LIBXSVF_MEM_XSVF_TDO_DATA = 1,
	LIBXSVF_MEM_XSVF_TDO_MASK = 2,
	LIBXSVF_MEM_XSVF_ADDR_MASK = 3,
	LIBXSVF_MEM_XSVF_DATA_MASK = 4,
	LIBXSVF_MEM_SVF_COMMANDBUF = 5,
	LIBXSVF_MEM_SVF_SDR_TDI_DATA = 6,
	LIBXSVF_MEM_SVF_SDR_TDI_MASK = 7,
	LIBXSVF_MEM_SVF_SDR_TDO_DATA = 8,
	LIBXSVF_MEM_SVF_SDR_TDO_MASK = 9,
	LIBXSVF_MEM_SVF_SDR_RET_MASK = 10,
	LIBXSVF_MEM_SVF_SIR_TDI_DATA = 11,
	LIBXSVF_MEM_SVF_SIR_TDI_MASK = 12,
	LIBXSVF_MEM_SVF_SIR_TDO_DATA = 13,
	LIBXSVF_MEM_SVF_SIR_TDO_MASK = 14,
	LIBXSVF_MEM_SVF_SIR_RET_MASK = 15,
	LIBXSVF_MEM_SVF_HDR_TDI_DATA = 16,
	LIBXSVF_MEM_SVF_HDR_TDI_MASK = 17,
	LIBXSVF_MEM_SVF_HDR_TDO_DATA = 18,
	LIBXSVF_MEM_SVF_HDR_TDO_MASK = 19,
	LIBXSVF_MEM_SVF_HDR_RET_MASK = 20,
	LIBXSVF_MEM_SVF_HIR_TDI_DATA = 21,
	LIBXSVF_MEM_SVF_HIR_TDI_MASK = 22,
	LIBXSVF_MEM_SVF_HIR_TDO_DATA = 23,
	LIBXSVF_MEM_SVF_HIR_TDO_MASK = 24,
	LIBXSVF_MEM_SVF_HIR_RET_MASK = 25,
	LIBXSVF_MEM_SVF_TDR_TDI_DATA = 26,
	LIBXSVF_MEM_SVF_TDR_TDI_MASK = 27,
	LIBXSVF_MEM_SVF_TDR_TDO_DATA = 28,
	LIBXSVF_MEM_SVF_TDR_TDO_MASK = 29,
	LIBXSVF_MEM_SVF_TDR_RET_MASK = 30,
	LIBXSVF_MEM_SVF_TIR_TDI_DATA = 31,
	LIBXSVF_MEM_SVF_TIR_TDI_MASK = 32,
	LIBXSVF_MEM_SVF_TIR_TDO_DATA = 33,
	LIBXSVF_MEM_SVF_TIR_TDO_MASK = 34,
	LIBXSVF_MEM_SVF_TIR_RET_MASK = 35,
	LIBXSVF_MEM_NUM = 36
};

struct libxsvf_host
{
	enum libxsvf_tap_state tap_state;
};

#endif

